name: CI/CD Pipeline

on:
  push:
    branches: [ "task_for_college" , "main" ]
  pull_request:
    branches: [ "task_for_college" , "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: run bot tests
        run: |
          pip install -r bot/requirements.txt
          pip install pytest httpx
          pytest bot/test_worker.py
      - name: run app tests
        run: |
          pip install -r requirements.txt
          pip install pytest httpx
          pytest tests/
